### ISSUE TITLE
B001 - Adam Driver plays faster than expected

### ISSUE THREAD

**Issue by cow203** [LMMilliken/DriverBot#1]
The first few seconds of the song are played at an increased speed!

Steps to reproduce:
1. Type "hey adam, play [Insert song title]"

Expected Result:
The song plays at the expected tempo.

Actual Result:
The start of the song plays at a quicker tempo than expected, sounds like it goes back to normal tempo after a few seconds

**Comment by LMMilliken** [comment]
Thanks for the heads up! This is an issue that has been reported before, and is actually an error on the user end! A quick fix is you stop taking crazy pills you goddam mad man. You are actually insane you know that? Noone believes you when you report bugs like this it is all in your head. The songs play at the right speed you cretin you fool i bet you just posted this to rile me up well guess what you succeeded. I am so sick of these internet trolls coming onto my repositories and ruining the vibe that I have going on over here. If you dont have anything constructive to say just get out. get out.

**Comment by cow203** [comment]
LGTM! PR Accepted
